### ISSUE TITLE
Not working, the developer tools report many errors

### ISSUE THREAD

**Issue by tiansin** [freshbitsweb/laravel-traveller#4]
```
ERR Cannot read property 'kind' of undefined: TypeError: Cannot read property 'kind' of undefined
	at r.getStaticCall (/Users/johnny/.vscode/extensions/freshbitsweb.laravel-traveller-1.5.0/dist/extension.js:6:104423)
	at r.getStaticCall (/Users/johnny/.vscode/extensions/freshbitsweb.laravel-traveller-1.5.0/dist/extension.js:6:104433)
	at r.getStaticCall (/Users/johnny/.vscode/extensions/freshbitsweb.laravel-traveller-1.5.0/dist/extension.js:6:104433)
	at r.traverseChildren (/Users/johnny/.vscode/extensions/freshbitsweb.laravel-traveller-1.5.0/dist/extension.js:6:104194)
	at r.traverseChildren (/Users/johnny/.vscode/extensions/freshbitsweb.laravel-traveller-1.5.0/dist/extension.js:6:104112)
	at r.getLinks (/Users/johnny/.vscode/extensions/freshbitsweb.laravel-traveller-1.5.0/dist/extension.js:6:103666)
	at T.provideDocumentLinks (/Users/johnny/.vscode/extensions/freshbitsweb.laravel-traveller-1.5.0/dist/extension.js:6:108611)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:644:350
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:54:761
```

**Comment by gauravmak** [comment]
Thanks for reporting. Possibly, some of the routes are causing issues. Is the extension working with the default Laravel installation? Can you please share sample routes from your routes file?

**Comment by tiansin** [comment]
```
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::group(['namespace' => 'Admin', 'prefix' => 'v1', 'middleware' => ['admin']], function (\Illuminate\Routing\Router $api) {
    $api->post('login', 'AuthController@authenticate')->name('admLogin');
    $api->get('image', 'HomeController@verify');


});
```

**Comment by gauravmak** [comment]
It is not working because you are using different syntax to specify routes:
`$api->` instead of `Route::`

I just pushed an update to prevent those errors and let other routes work which are defined as per the documentation. If you can change the routes to start with `Route::`, they should work too.

Thanks.

**Comment by tiansin** [comment]
@gauravmak The latest version has not been resolved and is still unusable.

**Comment by gauravmak** [comment]
The latest version is v1.5.1

To make sure that we are on the same page, you will need replace `$api->` with `Route::` to make the grouped routes work as per your example.

The first route (for logs) works already for me. If it is not working for you, can you please paster the logs from developer tools?

**Comment by tiansin** [comment]
@gauravmak The problem is still
```
 ERR Cannot read property 'kind' of undefined: TypeError: Cannot read property 'kind' of undefined
	at E.getGroupNamespace (/Users/johnny/.vscode/extensions/freshbitsweb.laravel-traveller-1.9.0/dist/extension.js:6:111424)
	at E.getGroupNamespace (/Users/johnny/.vscode/extensions/freshbitsweb.laravel-traveller-1.9.0/dist/extension.js:6:111619)
	at E.traverseChildren (/Users/johnny/.vscode/extensions/freshbitsweb.laravel-traveller-1.9.0/dist/extension.js:6:110594)
	at E.traverseChildren (/Users/johnny/.vscode/extensions/freshbitsweb.laravel-traveller-1.9.0/dist/extension.js:6:110709)
	at E.parse (/Users/johnny/.vscode/extensions/freshbitsweb.laravel-traveller-1.9.0/dist/extension.js:6:110192)
	at y.provideDocumentLinks (/Users/johnny/.vscode/extensions/freshbitsweb.laravel-traveller-1.9.0/dist/extension.js:6:112075)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:690:885
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:52:136
	at new Promise (<anonymous>)
	at Object.t.asPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:52:108)
	at $.provideLinks (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:690:856)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:705:515
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:695:632)
	at e.$provideDocumentLinks (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:705:493)
	at e._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:804:1013)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:804:705)
	at e._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:803:293)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:802:156)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:800:416
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:239:274)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:649
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:239:274)
	at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:243:629)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:240:824
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:236:737)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:236:89
	at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:245:185)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17
```

**Comment by gauravmak** [comment]
Can you share the route code please?
